# copy pasta into python console and you'll have yourself a db

# creating pokemon, type database w/population:

from app import db
from app import Pokemon

bulbasaur = Pokemon('bulbasaur')
ivysaur = Pokemon('ivysaur')
venusaur = Pokemon('venusaur')
charmander = Pokemon('charmander')
charmeleon = Pokemon('charmeleon')
charizard = Pokemon('charizard')
squirtle = Pokemon('squirtle')
wartortle = Pokemon('wartortle')
blastoise = Pokemon('blastoise')
caterpie = Pokemon('caterpie')
metapod = Pokemon('metapod')
butterfree = Pokemon('butterfree')
weedle = Pokemon('weedle')
kakuna = Pokemon('kakuna')
beedrill = Pokemon('beedrill')
pidgey = Pokemon('pidgey')
pidgeotto = Pokemon('pidgeotto')

db.session.add(bulbasaur)
db.session.add(ivysaur)
db.session.add(venusaur)
db.session.add(charmander)
db.session.add(charmeleon)
db.session.add(charizard)
db.session.add(squirtle)
db.session.add(wartortle)
db.session.add(blastoise)
db.session.add(caterpie)
db.session.add(metapod)
db.session.add(butterfree)
db.session.add(weedle)
db.session.add(kakuna)
db.session.add(beedrill)
db.session.add(pidgey)
db.session.add(pidgeotto)

from app import Type

normal = Type('normal')
fighting = Type('fighting')
flying = Type('flying')
poison = Type('poison')
ground = Type('ground')
rock = Type('rock')
bug = Type('bug')
ghost = Type('ghost')
steel = Type('steel')
fire = Type('fire')
water = Type('water')
grass = Type('grass')
electric = Type('electric')
psychic = Type('psychic')
ice = Type('ice')
dragon = Type('dragon')
dark = Type('dark')
fairy = Type('fairy')

db.session.add(normal)
db.session.add(fighting)
db.session.add(flying)
db.session.add(poison)
db.session.add(ground)
db.session.add(rock)
db.session.add(bug)
db.session.add(ghost)
db.session.add(steel)
db.session.add(fire)
db.session.add(water)
db.session.add(grass)
db.session.add(electric)
db.session.add(psychic)
db.session.add(ice)
db.session.add(dragon)
db.session.add(dark)
db.session.add(fairy)

db.session.commit()